mqtt_host: homeassistant.local
mqtt_port: 1883
log_level: INFO

ansible_shell_executable: /bin/bash

remote_home: "/home/{{ ansible_user }}"

camilladsp_version: "4.1.3"
camilladsp_samplerate: 44100
camilladsp_chunksize: 1024
camilladsp_format: S32_LE
camilladsp_port: 1234
camilladsp_install_dir: /usr/local/bin
camilladsp_config_dir: "{{ remote_home }}/camilladsp"

camillagui_version: "4.0.1"
camillagui_install_dir: "{{ remote_home }}/camillagui"
camillagui_port: 5005

beszel_version: "0.18.7"
beszel_agent_port: 45876
beszel_hub_host: beelink.local
beszel_agent_user: "{{ ansible_user }}"
