description: null
devices:
  adjust_period: null
  capture:
    channels: 2
    device: hw:0,1
    format: S32_LE
    labels: null
    link_mute_control: null
    link_volume_control: null
    stop_on_inactive: null
    type: Alsa
  capture_samplerate: null
  chunksize: 1024
  enable_rate_adjust: null
  multithreaded: true
  playback:
    channels: 2
    device: hw:2,0
    format: S32_LE
    type: Alsa
  queuelimit: null
  rate_measure_interval: null
  samplerate: 44100
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_limit: null
  volume_ramp_time: null
  worker_threads: null
filters:
  Bass:
    description: null
    parameters:
      freq: 85
      gain: 2
      q: 0.9
      type: Lowshelf
    type: Biquad
  Treble:
    description: null
    parameters:
      freq: 6500
      gain: -1
      q: 0.7
      type: Highshelf
    type: Biquad
mixers: null
pipeline:
- bypassed: null
  channels:
  - 0
  - 1
  description: null
  names:
  - Bass
  - Treble
  type: Filter
processors: null
title: Warm
