---
description:
devices:
  adjust_period:
  capture:
    channels: 2
    device: hw:0,1
    format: S32_LE
    labels:
    link_mute_control:
    link_volume_control:
    stop_on_inactive:
    type: Alsa
  capture_samplerate:
  chunksize: 1024
  enable_rate_adjust:
  multithreaded: true
  playback:
    channels: 2
    device: hw:2,0
    format: S32_LE
    type: Alsa
  queuelimit:
  rate_measure_interval:
  samplerate: 44100
  silence_threshold:
  silence_timeout:
  stop_on_rate_change:
  target_level:
  volume_limit:
  volume_ramp_time:
  worker_threads:
filters:
  Bass:
    description:
    parameters:
      freq: 85
      gain: 2
      q: 0.9
      type: Lowshelf
    type: Biquad
  Treble:
    description:
    parameters:
      freq: 6500
      gain: -1
      q: 0.7
      type: Highshelf
    type: Biquad
mixers:
pipeline:
  - bypassed:
    channels:
      - 0
      - 1
    description:
    names:
      - Bass
      - Treble
    type: Filter
processors:
title: Warm
