---
- name: Install Aswitch Deps
  ansible.builtin.pip:
    requirements: "{{ aswitch_app_dir }}/requirements.txt"
    virtualenv: "{{ aswitch_app_dir }}/.venv"
    virtualenv_command: python3 -m venv

- name: Restart Aswitch Services
  ansible.builtin.systemd:
    name: "{{ item.name }}.service"
    state: restarted
  loop: "{{ aswitch_services }}"
  become: true

- name: Reload And Restart Aswitch Services
  ansible.builtin.systemd:
    name: "{{ item.name }}.service"
    state: restarted
    daemon_reload: true
  loop: "{{ aswitch_services }}"
  become: true

- name: Refresh Dynamic Linker Cache
  ansible.builtin.command:
    cmd: ldconfig
  changed_when: true
  become: true
