---
aswitch_services_source_files:
  - "{{ playbook_dir }}/../../services/aswitch/aswitch.py"
  - "{{ playbook_dir }}/../../services/aswitch/audio_activity.py"
  - "{{ playbook_dir }}/../../services/aswitch/dac_status.py"
  - "{{ playbook_dir }}/../../services/aswitch/ir_logger.py"
  - "{{ playbook_dir }}/../../services/aswitch/preamp_ir_codes.py"

aswitch_disabled_services: []
aswitch_pigpio_src_dir: /usr/local/src/pigpio
aswitch_pigpio_git_ref: master
